services:
  mongo:
    image: mongo:7.0
    container_name: banana-mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=banana
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin --eval 'db.adminCommand({ ping: 1 })' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: banana-web
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
      - MONGODB_URI=mongodb://root:example@mongo:27017/banana?authSource=admin
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    ports:
      - "3300:3000"
    restart: unless-stopped

volumes:
  mongo_data:
